package com.ritchey.chapel.domain;

import java.io.Serializable;
import java.util.Date;

public class Absences implements Reflect, Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Absences.RecordNumber
     *
     * @mbggenerated Thu Nov 01 09:59:39 CDT 2012
     */
    private Integer recordnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Absences.People_Code_ID
     *
     * @mbggenerated Thu Nov 01 09:59:39 CDT 2012
     */
    private String peopleCodeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Absences.Date_Absent
     *
     * @mbggenerated Thu Nov 01 09:59:39 CDT 2012
     */
    private Date dateAbsent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Absences.AbsenceCount
     *
     * @mbggenerated Thu Nov 01 09:59:39 CDT 2012
     */
    private Double absencecount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Absences.Date_Tardy
     *
     * @mbggenerated Thu Nov 01 09:59:39 CDT 2012
     */
    private Date dateTardy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Absences.TardyCount
     *
     * @mbggenerated Thu Nov 01 09:59:39 CDT 2012
     */
    private Double tardycount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Absences.Dates_Deleted
     *
     * @mbggenerated Thu Nov 01 09:59:39 CDT 2012
     */
    private Date datesDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Absences.Reason_Deleted
     *
     * @mbggenerated Thu Nov 01 09:59:39 CDT 2012
     */
    private String reasonDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Absences
     *
     * @mbggenerated Thu Nov 01 09:59:39 CDT 2012
     */
    private static final long serialVersionUID = 20121101095939L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Absences.RecordNumber
     *
     * @return the value of Absences.RecordNumber
     *
     * @mbggenerated Thu Nov 01 09:59:39 CDT 2012
     */
    public Integer getRecordnumber() {
        return recordnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Absences.RecordNumber
     *
     * @param recordnumber the value for Absences.RecordNumber
     *
     * @mbggenerated Thu Nov 01 09:59:39 CDT 2012
     */
    public void setRecordnumber(Integer recordnumber) {
        this.recordnumber = recordnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Absences.People_Code_ID
     *
     * @return the value of Absences.People_Code_ID
     *
     * @mbggenerated Thu Nov 01 09:59:39 CDT 2012
     */
    public String getPeopleCodeId() {
        return peopleCodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Absences.People_Code_ID
     *
     * @param peopleCodeId the value for Absences.People_Code_ID
     *
     * @mbggenerated Thu Nov 01 09:59:39 CDT 2012
     */
    public void setPeopleCodeId(String peopleCodeId) {
        this.peopleCodeId = peopleCodeId == null ? null : peopleCodeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Absences.Date_Absent
     *
     * @return the value of Absences.Date_Absent
     *
     * @mbggenerated Thu Nov 01 09:59:39 CDT 2012
     */
    public Date getDateAbsent() {
        return dateAbsent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Absences.Date_Absent
     *
     * @param dateAbsent the value for Absences.Date_Absent
     *
     * @mbggenerated Thu Nov 01 09:59:39 CDT 2012
     */
    public void setDateAbsent(Date dateAbsent) {
        this.dateAbsent = dateAbsent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Absences.AbsenceCount
     *
     * @return the value of Absences.AbsenceCount
     *
     * @mbggenerated Thu Nov 01 09:59:39 CDT 2012
     */
    public Double getAbsencecount() {
        return absencecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Absences.AbsenceCount
     *
     * @param absencecount the value for Absences.AbsenceCount
     *
     * @mbggenerated Thu Nov 01 09:59:39 CDT 2012
     */
    public void setAbsencecount(Double absencecount) {
        this.absencecount = absencecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Absences.Date_Tardy
     *
     * @return the value of Absences.Date_Tardy
     *
     * @mbggenerated Thu Nov 01 09:59:39 CDT 2012
     */
    public Date getDateTardy() {
        return dateTardy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Absences.Date_Tardy
     *
     * @param dateTardy the value for Absences.Date_Tardy
     *
     * @mbggenerated Thu Nov 01 09:59:39 CDT 2012
     */
    public void setDateTardy(Date dateTardy) {
        this.dateTardy = dateTardy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Absences.TardyCount
     *
     * @return the value of Absences.TardyCount
     *
     * @mbggenerated Thu Nov 01 09:59:39 CDT 2012
     */
    public Double getTardycount() {
        return tardycount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Absences.TardyCount
     *
     * @param tardycount the value for Absences.TardyCount
     *
     * @mbggenerated Thu Nov 01 09:59:39 CDT 2012
     */
    public void setTardycount(Double tardycount) {
        this.tardycount = tardycount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Absences.Dates_Deleted
     *
     * @return the value of Absences.Dates_Deleted
     *
     * @mbggenerated Thu Nov 01 09:59:39 CDT 2012
     */
    public Date getDatesDeleted() {
        return datesDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Absences.Dates_Deleted
     *
     * @param datesDeleted the value for Absences.Dates_Deleted
     *
     * @mbggenerated Thu Nov 01 09:59:39 CDT 2012
     */
    public void setDatesDeleted(Date datesDeleted) {
        this.datesDeleted = datesDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Absences.Reason_Deleted
     *
     * @return the value of Absences.Reason_Deleted
     *
     * @mbggenerated Thu Nov 01 09:59:39 CDT 2012
     */
    public String getReasonDeleted() {
        return reasonDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Absences.Reason_Deleted
     *
     * @param reasonDeleted the value for Absences.Reason_Deleted
     *
     * @mbggenerated Thu Nov 01 09:59:39 CDT 2012
     */
    public void setReasonDeleted(String reasonDeleted) {
        this.reasonDeleted = reasonDeleted == null ? null : reasonDeleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Absences
     *
     * @mbggenerated Thu Nov 01 09:59:39 CDT 2012
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getName());
        sb.append("[");
        sb.append("Hash = ").append(hashCode());
        sb.append(",recordnumber=").append(recordnumber);
        sb.append(",peopleCodeId=").append(peopleCodeId);
        sb.append(",dateAbsent=").append(dateAbsent);
        sb.append(",absencecount=").append(absencecount);
        sb.append(",dateTardy=").append(dateTardy);
        sb.append(",tardycount=").append(tardycount);
        sb.append(",datesDeleted=").append(datesDeleted);
        sb.append(",reasonDeleted=").append(reasonDeleted);
        sb.append(",serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Absences
     *
     * @mbggenerated Thu Nov 01 09:59:39 CDT 2012
     */
    @Override
    public Object get(String name) {
        if (name.equals("recordnumber")) return recordnumber;
        if (name.equals("peopleCodeId")) return peopleCodeId;
        if (name.equals("dateAbsent")) return dateAbsent;
        if (name.equals("absencecount")) return absencecount;
        if (name.equals("dateTardy")) return dateTardy;
        if (name.equals("tardycount")) return tardycount;
        if (name.equals("datesDeleted")) return datesDeleted;
        if (name.equals("reasonDeleted")) return reasonDeleted;
        return null;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Absences
     *
     * @mbggenerated Thu Nov 01 09:59:39 CDT 2012
     */
    @Override
    public void set(String name, Object value) {
        if (name.equals("recordnumber")) recordnumber = value==null?null:(java.lang.Integer) value;
        if (name.equals("peopleCodeId")) peopleCodeId = value==null?null:(java.lang.String) value;
        if (name.equals("dateAbsent")) dateAbsent = value==null?null:(java.util.Date) value;
        if (name.equals("absencecount")) absencecount = value==null?null:(java.lang.Double) value;
        if (name.equals("dateTardy")) dateTardy = value==null?null:(java.util.Date) value;
        if (name.equals("tardycount")) tardycount = value==null?null:(java.lang.Double) value;
        if (name.equals("datesDeleted")) datesDeleted = value==null?null:(java.util.Date) value;
        if (name.equals("reasonDeleted")) reasonDeleted = value==null?null:(java.lang.String) value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Absences
     *
     * @mbggenerated Thu Nov 01 09:59:39 CDT 2012
     */
    @Override
    public void copy(Object a) {
        Absences castObject = (Absences) a;
        this.recordnumber = castObject.recordnumber;
        this.peopleCodeId = castObject.peopleCodeId;
        this.dateAbsent = castObject.dateAbsent;
        this.absencecount = castObject.absencecount;
        this.dateTardy = castObject.dateTardy;
        this.tardycount = castObject.tardycount;
        this.datesDeleted = castObject.datesDeleted;
        this.reasonDeleted = castObject.reasonDeleted;
    }

    public String simpleName() {
        return "Absences";
    }
}