package com.ritchey.chapel.domain;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface AbsencesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Absences
     *
     * @mbggenerated Thu Nov 01 09:59:39 CDT 2012
     */
    int countByExample(AbsencesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Absences
     *
     * @mbggenerated Thu Nov 01 09:59:39 CDT 2012
     */
    int deleteByExample(AbsencesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Absences
     *
     * @mbggenerated Thu Nov 01 09:59:39 CDT 2012
     */
    int deleteByPrimaryKey(Integer recordnumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Absences
     *
     * @mbggenerated Thu Nov 01 09:59:39 CDT 2012
     */
    int insert(Absences record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Absences
     *
     * @mbggenerated Thu Nov 01 09:59:39 CDT 2012
     */
    int insertSelective(Absences record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Absences
     *
     * @mbggenerated Thu Nov 01 09:59:39 CDT 2012
     */
    List<Absences> selectByExample(AbsencesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Absences
     *
     * @mbggenerated Thu Nov 01 09:59:39 CDT 2012
     */
    Absences selectByPrimaryKey(Integer recordnumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Absences
     *
     * @mbggenerated Thu Nov 01 09:59:39 CDT 2012
     */
    int updateByExampleSelective(@Param("record") Absences record, @Param("example") AbsencesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Absences
     *
     * @mbggenerated Thu Nov 01 09:59:39 CDT 2012
     */
    int updateByExample(@Param("record") Absences record, @Param("example") AbsencesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Absences
     *
     * @mbggenerated Thu Nov 01 09:59:39 CDT 2012
     */
    int updateByPrimaryKeySelective(Absences record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Absences
     *
     * @mbggenerated Thu Nov 01 09:59:39 CDT 2012
     */
    int updateByPrimaryKey(Absences record);
}